#!/usr/bin/env node
/**
 * Synthesize the sound effects (CO-102). `npm run audio:gen`.
 *
 *   out  public/assets/audio/<key>.wav   one clip per `SOUND_KEYS` entry
 *
 * Every clip is generated from the recipes below with `lib/synth.mjs`, so the
 * whole set is original work under the repository licence (see
 * `public/assets/audio/CREDITS.md`) and can be regenerated byte-for-byte.
 * The key list is the one `src/config/sounds.ts` ships; a recipe missing for a
 * key or a key missing for a recipe fails the run, so the two cannot drift.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { concat, envelope, mix, noise, normalize, square, sweep, wavBytes } from './lib/synth.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'public', 'assets', 'audio');
const CONFIG = join(ROOT, 'src', 'config', 'sounds.ts');

/** A short tone with a fast attack: the building block of the UI and pickup voices. */
const ping = (seconds, fromHz, toHz, shape) =>
  envelope(sweep(seconds, fromHz, toHz, undefined, shape), 0.005);

const RECIPES = {
  'cast.fire': () =>
    mix([envelope(noise(0.3, 11, 1200), 0.02), 0.8], [envelope(sweep(0.3, 320, 110), 0.02), 0.5]),
  'cast.ice': () =>
    mix([ping(0.28, 1100, 1900), 0.6], [envelope(noise(0.28, 12, 6000), 0.01), 0.15]),
  'cast.lightning': () =>
    mix([envelope(noise(0.16, 13, 9000), 0.002), 0.8], [ping(0.16, 2400, 900, square), 0.25]),
  'cast.earth': () =>
    mix([envelope(sweep(0.32, 95, 45), 0.01), 0.9], [envelope(noise(0.12, 14, 400), 0.005), 0.5]),

  'enemy.hurt': () =>
    mix([envelope(noise(0.08, 21, 3000), 0.002), 0.7], [ping(0.08, 420, 300), 0.5]),
  'enemy.death': () => envelope(sweep(0.22, 520, 140, undefined, square), 0.005),

  'player.hurt': () =>
    mix([ping(0.16, 240, 180, square), 0.6], [envelope(noise(0.16, 31, 2500), 0.002), 0.5]),
  'player.lowHealth': () =>
    concat(ping(0.1, 880, 880), new Array(1100).fill(0), ping(0.1, 880, 880)),
  'player.death': () =>
    mix([envelope(sweep(0.75, 420, 55), 0.01), 0.9], [envelope(noise(0.75, 32, 900), 0.01), 0.3]),

  'progress.gem': () => ping(0.12, 1400, 2100),
  'progress.levelUp': () =>
    concat(ping(0.13, 523, 523), ping(0.13, 659, 659), ping(0.26, 784, 784)),
  'progress.perk': () => concat(ping(0.1, 660, 660), ping(0.2, 990, 990)),

  'boss.spawn': () =>
    mix([envelope(noise(0.9, 41, 350), 0.15), 0.8], [envelope(sweep(0.9, 70, 50), 0.15), 0.7]),
  'boss.telegraph': () => envelope(sweep(0.42, 200, 620), 0.05),
  'boss.charge': () =>
    mix([envelope(noise(0.3, 42, 1500), 0.01), 0.8], [envelope(sweep(0.3, 160, 80), 0.01), 0.6]),
  'boss.death': () =>
    mix([envelope(sweep(1.0, 300, 35), 0.02), 0.9], [envelope(noise(1.0, 43, 700), 0.02), 0.4]),

  'ui.move': () => ping(0.04, 1000, 1000),
  'ui.confirm': () => ping(0.1, 880, 1320),
  'ui.back': () => ping(0.1, 660, 440),
};

/** The keys `src/config/sounds.ts` declares, read off the `SOUND_KEYS` literal. */
function configuredKeys() {
  const source = readFileSync(CONFIG, 'utf8');
  const block = source.match(/SOUND_KEYS = \[([\s\S]*?)\] as const/);
  if (!block) throw new Error(`could not find SOUND_KEYS in ${CONFIG}`);
  return [...block[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
}

const keys = configuredKeys();
const missingRecipe = keys.filter((key) => !RECIPES[key]);
const missingKey = Object.keys(RECIPES).filter((key) => !keys.includes(key));
if (missingRecipe.length || missingKey.length) {
  console.error(`recipes without a key: ${missingKey.join(', ') || 'none'}`);
  console.error(`keys without a recipe: ${missingRecipe.join(', ') || 'none'}`);
  process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });
let bytes = 0;
for (const key of keys) {
  const wav = wavBytes(normalize(RECIPES[key]()));
  writeFileSync(join(OUT_DIR, `${key}.wav`), wav);
  bytes += wav.length;
}
console.log(`wrote ${keys.length} clips (${(bytes / 1024).toFixed(0)} KiB) to public/assets/audio`);
