#!/usr/bin/env node
/**
 * Synthesize the sound effects (CO-102). `npm run audio:gen`.
 *
 *   out  public/assets/audio/<key>.wav   one clip per `SOUND_KEYS` entry,
 *                                        one loop per `MUSIC_KEYS` entry (CO-157)
 *
 * Every clip but the sourced ones is generated from the recipes below with
 * `lib/synth.mjs`, so it is original work under the repository licence (see
 * `public/assets/audio/CREDITS.md`) and can be regenerated byte-for-byte.
 * The fire spells' cues are built on the sourced `cast.fire` clip (CO-158), so
 * they are regenerated from the committed copy of it.
 * The keys in `lib/sourcedAudio.mjs` are recorded clips (CO-177): this script
 * never writes them; `npm run audio:cut` does.
 * The key list is the one `src/config/sounds.ts` ships. Each key needs a
 * recipe or a sourced clip, never both, and every recipe or sourced clip needs
 * a key, or the run fails, so the lists cannot drift. The music tracks are
 * checked the same way against `lib/music.mjs`.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MUSIC_RECIPES } from './lib/music.mjs';
import { SOURCED } from './lib/sourcedAudio.mjs';
import {
  concat,
  envelope,
  mix,
  noise,
  normalize,
  readWav,
  resample,
  square,
  sweep,
  wavBytes,
} from './lib/synth.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'public', 'assets', 'audio');
const CONFIG = join(ROOT, 'src', 'config', 'sounds.ts');

/** A short tone with a fast attack: the building block of the UI and pickup voices. */
const ping = (seconds, fromHz, toHz, shape) =>
  envelope(sweep(seconds, fromHz, toHz, undefined, shape), 0.005);

/**
 * Fire Bolt's sourced whoosh (`cast.fire`, CO-177) as it ships, read fresh per
 * call. The other fire spells are built on it (CO-158) so the element sounds of
 * a piece; a re-cut of `cast.fire` means running this script again.
 */
const fireWhoosh = () => readWav(readFileSync(join(OUT_DIR, 'cast.fire.wav')));

/** A short low knock: the building block of Earth's stones. */
const thud = (seconds, fromHz, toHz, seed) =>
  mix(
    [envelope(sweep(seconds, fromHz, toHz), 0.004), 0.9],
    [envelope(noise(seconds, seed, 600), 0.002), 0.5],
  );

/** A bright crackle with a falling buzz under it: the building block of Lightning. */
const zap = (seconds, fromHz, toHz, seed) =>
  mix(
    [envelope(noise(seconds, seed, 9000), 0.002), 0.8],
    [ping(seconds, fromHz, toHz, square), 0.25],
  );

/**
 * One cast cue per roster spell (CO-158). Each element shares a base voice —
 * Fire the sourced whoosh, Ice a high glassy ping, Lightning a crackle over a
 * square buzz, Earth a low knock — and each spell changes its pitch, length or
 * layers, so a loadout can be told apart by ear and still sound like one
 * element. Always-on spells (the shields, the sword) cue as they come up.
 */
export const RECIPES = {
  'cast.fire_meteor': () =>
    // Slowed and deepened, with a whistle falling in: something big incoming.
    mix([resample(fireWhoosh(), 0.6), 0.8], [envelope(sweep(0.9, 900, 160), 0.15), 0.3]),
  'cast.fire_column': () =>
    // A slower whoosh over a roar that swells: a wall of flame rolling out.
    mix(
      [resample(fireWhoosh(), 0.8), 0.7],
      [envelope(noise(0.75, 71, 1400), 0.2), 0.7],
      [envelope(sweep(0.75, 140, 90), 0.2), 0.3],
    ),
  'cast.fire_companion': () =>
    // Sped up to a small spit, for a caster that fires every second.
    mix([resample(fireWhoosh(), 1.7), 0.9], [envelope(noise(0.06, 72, 5000), 0.002), 0.3]),
  'cast.fire_dragon': () =>
    // The whoosh under a low square growl: a breath, not a spark.
    mix(
      [resample(fireWhoosh(), 0.75), 0.75],
      [envelope(sweep(0.7, 120, 70, undefined, square), 0.04), 0.18],
      [envelope(noise(0.7, 73, 900), 0.04), 0.4],
    ),

  'cast.ice': () =>
    mix([ping(0.28, 1100, 1900), 0.6], [envelope(noise(0.28, 12, 6000), 0.01), 0.15]),
  'cast.ice_nova_bomb': () =>
    // The ping turned over and falling, a fifth above it: a shard lobbed away.
    mix(
      [ping(0.26, 1500, 700), 0.55],
      [ping(0.26, 2250, 1050), 0.25],
      [envelope(noise(0.26, 74, 5000), 0.01), 0.15],
    ),
  'cast.ice_shield': () =>
    // A slow-rising pair of tones: a shell forming, nothing like `shield.hit`'s tick.
    mix(
      [envelope(sweep(0.45, 1320, 1760), 0.06), 0.5],
      [envelope(sweep(0.45, 1980, 2640), 0.06), 0.3],
      [envelope(noise(0.45, 75, 7000), 0.1), 0.12],
    ),
  'cast.ice_companion': () =>
    // Half the default's length and higher, for a caster that fires every 1.4 s.
    mix([ping(0.13, 1600, 2600), 0.6], [envelope(noise(0.13, 76, 6000), 0.005), 0.15]),
  'cast.ice_blizzard': () =>
    // A wind that builds, with a thin whistle riding it.
    mix([envelope(noise(1.0, 77, 2800), 0.3), 0.8], [envelope(sweep(1.0, 900, 1400), 0.3), 0.2]),

  'cast.lightning': () =>
    mix([envelope(noise(0.16, 13, 9000), 0.002), 0.8], [ping(0.16, 2400, 900, square), 0.25]),
  'cast.lightning_chain': () =>
    // Three zaps stepping down: one arc jumping from target to target.
    concat(zap(0.06, 2800, 1800, 78), zap(0.06, 2300, 1400, 79), zap(0.09, 1800, 900, 80)),
  'cast.lightning_tornado': () =>
    // A crackling wind whose buzz whirls upward.
    mix(
      [envelope(noise(0.9, 81, 5000), 0.3), 0.7],
      [envelope(sweep(0.9, 300, 900, undefined, square), 0.3), 0.12],
      [envelope(noise(0.9, 82, 9000), 0.3), 0.2],
    ),
  'cast.lightning_companion': () =>
    // The default's crackle, cut short and pitched up.
    zap(0.08, 3400, 1800, 83),
  'cast.lightning_sword': () =>
    // A rising buzz over a crackle: a blade drawn and charged.
    mix(
      [envelope(sweep(0.3, 600, 2400, undefined, square), 0.03), 0.25],
      [envelope(noise(0.3, 84, 9000), 0.03), 0.5],
      [envelope(sweep(0.3, 1200, 4800), 0.03), 0.2],
    ),

  'cast.earth': () =>
    mix([envelope(sweep(0.32, 95, 45), 0.01), 0.9], [envelope(noise(0.12, 14, 400), 0.005), 0.5]),
  'cast.earth_boulder': () =>
    // A longer, softer-edged rumble: a stone set rolling.
    mix([envelope(sweep(0.45, 75, 55), 0.05), 0.9], [envelope(noise(0.45, 85, 300), 0.05), 0.7]),
  'cast.earth_shield': () =>
    // Three knocks rising in pitch: stones lifting into a ring.
    concat(thud(0.08, 120, 80, 86), thud(0.08, 150, 100, 87), thud(0.14, 190, 120, 88)),
  'cast.earth_quake': () =>
    // The deepest and longest: the ground itself.
    mix(
      [envelope(noise(1.0, 89, 200), 0.1), 0.9],
      [envelope(sweep(1.0, 55, 35), 0.1), 0.8],
      [envelope(sweep(1.0, 45, 40, undefined, square), 0.1), 0.1],
    ),
  'cast.earth_companion': () =>
    // One short, higher knock, for a caster that fires every 1.6 s.
    thud(0.14, 170, 75, 90),

  'enemy.hurt': () =>
    mix([envelope(noise(0.08, 21, 3000), 0.002), 0.7], [ping(0.08, 420, 300), 0.5]),

  'player.hurt': () =>
    mix([ping(0.16, 240, 180, square), 0.6], [envelope(noise(0.16, 31, 2500), 0.002), 0.5]),
  'player.lowHealth': () =>
    concat(ping(0.1, 880, 880), new Array(1100).fill(0), ping(0.1, 880, 880)),
  'player.death': () =>
    mix([envelope(sweep(0.75, 420, 55), 0.01), 0.9], [envelope(noise(0.75, 32, 900), 0.01), 0.3]),

  // #384: a whoosh that falls as the hero lands, noise-led so it is nothing like
  // `player.hurt`'s buzz; and a soft rising ping, quieter and shorter than a pickup's.
  'player.dash': () =>
    mix([envelope(noise(0.2, 33, 3500), 0.03), 0.8], [envelope(sweep(0.2, 700, 220), 0.02), 0.35]),
  'player.dashReady': () => ping(0.09, 1320, 1760),

  'progress.perk': () => concat(ping(0.1, 660, 660), ping(0.2, 990, 990)),

  // A magnet or a bomb plays its grab and its effect on the same frame, so the
  // grab is a short blip and the effect carries the sound.
  'pickup.ember': () => ping(0.1, 780, 1170),
  'pickup.relic': () =>
    mix(
      [concat(ping(0.08, 784, 784), ping(0.08, 1047, 1047), ping(0.24, 1568, 1568)), 0.8],
      [envelope(noise(0.4, 51, 7000), 0.05), 0.1],
    ),
  'pickup.health': () => ping(0.22, 440, 880),
  'pickup.magnet': () => ping(0.06, 620, 930, square),
  'pickup.bomb': () => ping(0.06, 330, 440, square),
  'pickup.chest': () =>
    concat(ping(0.06, 523, 523), ping(0.06, 659, 659), ping(0.06, 784, 784), ping(0.2, 1047, 1047)),
  'pickup.magnetPull': () =>
    mix([envelope(sweep(0.6, 200, 720), 0.25), 0.7], [envelope(noise(0.6, 52, 2500), 0.25), 0.3]),
  'pickup.bombBlast': () =>
    mix([envelope(noise(0.7, 53, 800), 0.003), 0.9], [envelope(sweep(0.7, 120, 35), 0.003), 0.8]),

  // Glassy and high, a sine not a square: nothing like `player.hurt`'s buzz.
  'shield.hit': () =>
    mix(
      [ping(0.07, 2600, 2400), 0.6],
      [ping(0.07, 3900, 3600), 0.3],
      [envelope(noise(0.03, 61, 9000), 0.001), 0.3],
    ),
  'shield.break': () =>
    mix(
      [envelope(noise(0.45, 62, 7000), 0.002), 0.8],
      [ping(0.45, 2200, 700), 0.4],
      [ping(0.3, 3300, 1500), 0.25],
    ),

  'boss.spawn': () =>
    mix([envelope(noise(0.9, 41, 350), 0.15), 0.8], [envelope(sweep(0.9, 70, 50), 0.15), 0.7]),
  'boss.telegraph': () => envelope(sweep(0.42, 200, 620), 0.05),
  'boss.charge': () =>
    mix([envelope(noise(0.3, 42, 1500), 0.01), 0.8], [envelope(sweep(0.3, 160, 80), 0.01), 0.6]),
  'boss.death': () =>
    mix([envelope(sweep(1.0, 300, 35), 0.02), 0.9], [envelope(noise(1.0, 43, 700), 0.02), 0.4]),

  'ui.move': () => ping(0.04, 1000, 1000),
  'ui.confirm': () => ping(0.1, 880, 1320),
  'ui.back': () => ping(0.1, 660, 440),
};

/**
 * The keys `src/config/sounds.ts` declares, read off the `SOUND_KEYS` literal,
 * or another key list's (`MUSIC_KEYS`).
 */
export function configuredKeys(list = 'SOUND_KEYS') {
  const source = readFileSync(CONFIG, 'utf8');
  const block = source.match(new RegExp(`${list} = \\[([\\s\\S]*?)\\] as const`));
  if (!block) throw new Error(`could not find ${list} in ${CONFIG}`);
  return [...block[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
}

/** What stops a run: keys with no clip, keys with two, and clips with no key. */
export function keyProblems(keys, recipeKeys, sourcedKeys) {
  return {
    noClip: keys.filter((key) => !recipeKeys.includes(key) && !sourcedKeys.includes(key)),
    both: recipeKeys.filter((key) => sourcedKeys.includes(key)),
    noKey: [...recipeKeys, ...sourcedKeys].filter((key) => !keys.includes(key)),
  };
}

function main() {
  const keys = configuredKeys();
  const problems = keyProblems(keys, Object.keys(RECIPES), Object.keys(SOURCED));
  const music = keyProblems(configuredKeys('MUSIC_KEYS'), Object.keys(MUSIC_RECIPES), []);
  if (music.noClip.length || music.noKey.length) {
    console.error(`music keys without a recipe: ${music.noClip.join(', ') || 'none'}`);
    console.error(`music recipes without a key: ${music.noKey.join(', ') || 'none'}`);
    process.exit(1);
  }
  if (problems.noClip.length || problems.both.length || problems.noKey.length) {
    console.error(
      `keys without a recipe or a sourced clip: ${problems.noClip.join(', ') || 'none'}`,
    );
    console.error(`keys with both: ${problems.both.join(', ') || 'none'}`);
    console.error(`recipes or sourced clips without a key: ${problems.noKey.join(', ') || 'none'}`);
    process.exit(1);
  }

  mkdirSync(OUT_DIR, { recursive: true });
  let bytes = 0;
  for (const key of Object.keys(RECIPES)) {
    const wav = wavBytes(normalize(RECIPES[key]()));
    writeFileSync(join(OUT_DIR, `${key}.wav`), wav);
    bytes += wav.length;
  }
  let musicBytes = 0;
  for (const [key, recipe] of Object.entries(MUSIC_RECIPES)) {
    const wav = wavBytes(normalize(recipe.render(recipe)));
    writeFileSync(join(OUT_DIR, `${key}.wav`), wav);
    musicBytes += wav.length;
  }
  console.log(
    `wrote ${Object.keys(RECIPES).length} clips (${(bytes / 1024).toFixed(0)} KiB) and ` +
      `${Object.keys(MUSIC_RECIPES).length} tracks (${(musicBytes / 1024).toFixed(0)} KiB) to public/assets/audio; ` +
      `left ${Object.keys(SOURCED).length} sourced clips alone`,
  );
}

// Imported by the unit tests for `RECIPES` and `keyProblems`; only a direct run writes files.
if (process.argv[1] === fileURLToPath(import.meta.url)) main();
